site_name: Guide utilisateur
nav:
    - Bienvenue: index.md
    - Démarrer:
      - Les espaces & collections: gs/index.md
      - Les indicateurs: gs/metrics.md
      - Les tableaux et graphiques: gs/charts.md
    - Suivre les indicateurs:
      - Le compte utilisateur: favs/index.md
      - Favoris & alertes: favs/favs-alerts.md
      - Tableaux de bord: favs/dashboards.md
    - Utiliser Statit dans Excel:
      - Installer le complément Excel: excel/index.md
      - Accéder aux indicateurs: excel/access.md
    - Référence:
      - Introduction: reference/index.md
theme:
  name: material
  palette:
    primary: white
    secondary: black
    accent: orange
  logo: img/logo_statit_64.png
  favicon: img/favicon.ico
  language: fr
  features:
    #- navigation.tabs
    - navigation.indexes
    - navigation.sections
    - navigation.instant
    - navigation.tracking
extra:
  generator: false #this should remove the Made with Material at the bottom - not working
  homepage: https://gostatit.com
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
